### ISSUE TITLE
I cant find whats wrong does anyone know

### ISSUE THREAD

**Issue by Realms2111** [jtorleonstudios/HUB-Library-Ferret#13]
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 5/7/23 2:43 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin
        ... more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin
	... more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 56 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

==> [LOG].txt

**Comment by jtorleonstudios** [comment]
please add upload the complet log here

**Comment by jtorleonstudios** [comment]
reopen issue with the log file (append the file in comment)
thanks you

**Comment by Realms2111** [comment]
[Uploading crash-2023-05-07_17.59.17-client.txt…]()
